Autoventas/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Autoventas.Models;

namespace Autoventas.Controllers
{
    public class CuentaController : Controller
    {
        public DB_Autoventas db = new DB_Autoventas();

        // GET: Cuenta
        public ActionResult Login()
        {
            if(Session["idUsuario"]!=null){
                return RedirectToAction("../Home/Index");
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Login(Usuario usuario)
        {
            var usr = db.usuario.FirstOrDefault(u => u.correo == usuario.correo && u.contraseña == usuario.contraseña);
            if(usr!=null){
                Session["nombreUsuario"] = usr.nombre;
                Session["idUsuario"] = usr.idUsuario;
                Session["idRol"] = usr.rol.idRol;
                return VerificarSesion();
            }
            else
            {
                ModelState.AddModelError("", "Correo o Contraseña Incorrectos... Verifique sus Credenciales");
            }
            return View();
        }
        // GET: Cuenta
        public ActionResult Registro()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Registro(Usuario usuario)
        {
            if(ModelState.IsValid ){
                Rol rol = db.rol.FirstOrDefault(r => r.idRol == 2);
                usuario.rol = rol;
                db.usuario.Add(usuario);
                db.SaveChanges();
            }
            return RedirectToAction("Login");
        }
        // GET: Cuenta
        public ActionResult ListarUsuarios(string search)
        {
            var usuarios = from u in db.usuario
                            select u;
            if (!String.IsNullOrEmpty(search))
            {
                usuarios = usuarios.Where(u => u.nombre.Contains(search));
            }
            usuarios = usuarios.OrderBy(v => v.nombre);
            return View(usuarios.ToList());
        }
        // GET: Cuenta
        public ActionResult CrearAdministrador()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CrearAdministrador(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                Rol rol = db.rol.FirstOrDefault(r => r.idRol == 1);
                usuario.rol = rol;
                db.usuario.Add(usuario);
                db.SaveChanges();
                ViewBag.mensaje = "El Administrador " + usuario.nombre + " Fue Creado Correctamente";
            }
            return View();
        }
        // GET: Vehiculo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.usuario.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.usuario.Find(id);
            db.usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("ListarUsuarios");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult VerificarSesion()
        {
            if(Session["idUsuario"]!=null){
                return RedirectToAction("../Home/Index");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
        public ActionResult Logout()
        {
            Session.Remove("idUsuario");
            Session.Remove("nombreUsuario");
            Session.Remove("rol");
            return RedirectToAction("Login");
        }
        // GET: Venta/Details/5
        public ActionResult Details()
        {
            Usuario usuario = db.usuario.Find(Session["idUsuario"]);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        public ActionResult Edit()
        {
            Usuario usuario = db.usuario.Find(Session["idUsuario"]);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        // POST: Venta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("../Home/Index");
            }
            return View(usuario);
        }
    }
}

Autoventas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Autoventas.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Autoventas/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Autoventas.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace Autoventas.Controllers
{
    public class VentaController : Controller
    {
        private DB_Autoventas db = new DB_Autoventas();

        // GET: Venta
        public ActionResult Index(string search)
        {
            var ventas = from v in db.venta
                            select v;
            if (!String.IsNullOrEmpty(search))
            {
                ventas = ventas.Where(v => v.vehiculo.marca.ToString().Contains(search));
            }
            ventas = ventas.OrderBy(v => v.vehiculo.marca);

            return View(ventas.ToList());
        }

        // GET: Venta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }
        // GET: Venta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Venta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idVenta,fecha,forma")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venta);
        }

        // GET: Venta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Venta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venta venta = db.venta.Find(id);
            db.venta.Remove(venta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Reporte()
        {
            // Creamos el documento con el tamaño de página tradicional
            Document doc = new Document(PageSize.LETTER);
            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + " //reporte" + DateTime.Now.Day+"_"+DateTime.Now.Month+"_"+DateTime.Now.Day+"_"+DateTime.Now.Hour+"_"+DateTime.Now.Second+".pdf";
            // Indicamos donde vamos a guardar el documento
            PdfWriter writer = PdfWriter.GetInstance(doc,
                                        new FileStream(path, FileMode.Create));

            // Le colocamos el título y el autor
            // **Nota: Esto no será visible en el documento
            doc.AddTitle("Reporte");
            doc.AddCreator("Autoventas  Cars");

            // Abrimos el archivo
            doc.Open();

            // Creamos el tipo de Font que vamos utilizar
            iTextSharp.text.Font _standardFont = new iTextSharp.text.Font(iTextSharp.text.Font.FontFamily.HELVETICA, 8, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

            // Escribimos el encabezamiento en el documento
            doc.Add(new Paragraph("Reporte de Ventas"));
            doc.Add(Chunk.NEWLINE);

            // Creamos una tabla que contendrá el nombre, apellido y país
            // de nuestros visitante.
            PdfPTable tblPrueba = new PdfPTable(7);
            tblPrueba.WidthPercentage = 100;

            // Configuramos el título de las columnas de la tabla
            PdfPCell clNombre = new PdfPCell(new Phrase("Nombre", _standardFont));
            clNombre.BorderWidth = 0;
            clNombre.BorderWidthBottom = 0.75f;

            PdfPCell clMarca = new PdfPCell(new Phrase("Marca", _standardFont));
            clMarca.BorderWidth = 0;
            clMarca.BorderWidthBottom = 0.75f;

            PdfPCell clModelo = new PdfPCell(new Phrase("Modelo", _standardFont));
            clModelo.BorderWidth = 0;
            clModelo.BorderWidthBottom = 0.75f;

            PdfPCell clCompra = new PdfPCell(new Phrase("Precio de Compra", _standardFont));
            clCompra.BorderWidth = 0;
            clCompra.BorderWidthBottom = 0.75f;

            PdfPCell clPrecio = new PdfPCell(new Phrase("Precio de Venta", _standardFont));
            clPrecio.BorderWidth = 0;
            clPrecio.BorderWidthBottom = 0.75f;

            PdfPCell clGanancia = new PdfPCell(new Phrase("Ganancia", _standardFont));
            clGanancia.BorderWidth = 0;
            clGanancia.BorderWidthBottom = 0.75f;

            PdfPCell clFecha = new PdfPCell(new Phrase("Fecha", _standardFont));
            clFecha.BorderWidth = 0;
            clFecha.BorderWidthBottom = 0.75f;
            // Añadimos las celdas a la tabla
            tblPrueba.AddCell(clNombre);
            tblPrueba.AddCell(clMarca);
            tblPrueba.AddCell(clModelo);
            tblPrueba.AddCell(clCompra);
            tblPrueba.AddCell(clPrecio);
            tblPrueba.AddCell(clGanancia);
            tblPrueba.AddCell(clFecha);

            // Llenamos la tabla con información
            
            foreach(var venta in db.venta)
            {
                clNombre = new PdfPCell(new Phrase(venta.usuario.nombre, _standardFont));
                clNombre.BorderWidth = 0;

                clMarca = new PdfPCell(new Phrase(venta.vehiculo.marca.ToString(), _standardFont));
                clMarca.BorderWidth = 0;

                clModelo = new PdfPCell(new Phrase(venta.vehiculo.modelo, _standardFont));
                clModelo.BorderWidth = 0;

                clCompra = new PdfPCell(new Phrase(venta.vehiculo.precioCompra.ToString(), _standardFont));
                clCompra.BorderWidth = 0;

                clPrecio = new PdfPCell(new Phrase(venta.vehiculo.precio.ToString(), _standardFont));
                clPrecio.BorderWidth = 0;

                clGanancia = new PdfPCell(new Phrase(venta.ganancia.ToString(), _standardFont));
                clGanancia.BorderWidth = 0;

                clFecha = new PdfPCell(new Phrase(venta.fecha.ToString(), _standardFont));
                clFecha.BorderWidth = 0;
            }

            // Añadimos las celdas a la tabla
            tblPrueba.AddCell(clNombre);
            tblPrueba.AddCell(clMarca);
            tblPrueba.AddCell(clModelo);
            tblPrueba.AddCell(clCompra);
            tblPrueba.AddCell(clPrecio);
            tblPrueba.AddCell(clGanancia);
            tblPrueba.AddCell(clFecha);

            // Finalmente, añadimos la tabla al documento PDF y cerramos el documento
            doc.Add(tblPrueba);

            doc.Close();
            writer.Close();

            return RedirectToAction("Index");
        }
    }
}

Autoventas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}
@if (Session["idUsuario"] != null && "1".Equals(Session["idRol"].ToString()))
{
    <h2>Bienvenido @Session["nombreUsuario"] </h2>
    <h3>Panel de Administracion</h3>
    <br><br>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/usuarios.png" alt="Usuarios... " height="100" width="100">
                <div class="caption">
                    <h2>Usuarios</h2>
                    <p>@Html.ActionLink("Ver Usuarios", "ListarUsuarios", "Cuenta", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/ventas.png" alt="Ventas" height="100" width="100">
                <div class="caption">
                    <h2>Ventas</h2>
                    <p>@Html.ActionLink("Ventas", "Index", "Venta", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/EditarUsuario.png" alt="Usuario" height="100" width="100">
                <div class="caption">
                    <h2>Mi Usuario</h2>
                    <p>@Html.ActionLink("Mi Usuario", "Details", "Cuenta", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4"><br />
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/vehiculos.png" alt="Vehiculos" height="150" width="150">
                <div class="caption">
                    <h2>Vehiculos</h2>
                    <p>@Html.ActionLink("Vehiculos", "Index", "Vehiculo", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
    </div>
}
@if (Session["idUsuario"] != null && "2".Equals(Session["idRol"].ToString()))
{
    <h2>Bienvenido @Session["nombreUsuario"] </h2>
    <h3>Inicio</h3>
    <br><br>
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/Reserva.png" alt="Reservas" height="100" width="100">
                <div class="caption">
                    <h2>Mis Reservas</h2>
                    <p>@Html.ActionLink("Ver", "Index", "Apartado", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/compra.png" alt="Compras" height="100" width="100">
                <div class="caption">
                    <h2>Mis Compras</h2>
                    <p>@Html.ActionLink("Ver", "Index", "Venta", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="~/Recursos/Imgenes/EditarUsuario.png" alt="Usuario" height="100" width="100">
                <div class="caption">
                    <h2>Mi Usuario</h2>
                    <p>@Html.ActionLink("Mi Usuario", "Details", "Cuenta", new { area = "" }, new { @class = "btn btn-primary" })</p>
                </div>
            </div>
        </div>
    </div>
}
@if (Session["idUsuario"] == null)
{
            <h2>Por Favor, Inicie Sesion </h2>
            <div>
                @Html.ActionLink("Iniciar Sesion", "Login", "Cuenta")
            </div>
}