Autoventas/Models/Apartado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Autoventas.Models
{
    public class Apartado
    {
        [Key]
        public int idApartado { set; get; }
        [Display(Name = "Fecha")]
        [Required(ErrorMessage = "Este Campo es Obligatorio"), DataType(DataType.Date)]
        public DateTime fecha { get; set; }
        public virtual Usuario usuario { set; get; }
        public virtual Vehiculo vehiculo { set; get; }
    }
}

Autoventas/Models/Venta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace Autoventas.Models
{
    public enum FormaPago
    {
        Tarjeta, Deposito 
    }
    public class Venta
    {
        [Key]
        public int idVenta {set; get; }
        [Display(Name = "Fecha")]
        [Required(ErrorMessage = "Este Campo es Obligatorio"), DataType(DataType.Date)]
        public DateTime fecha {get; set; }
        [Display(Name = "Forma de Pago")]
        [Required(ErrorMessage = "Este Campo es Obligatorio")]
        public FormaPago? forma { get; set; }
        [Display(Name = "Ganancia")]
        [Required(ErrorMessage = "Este Campo es Obligatorio")]
        public int ganancia { get; set; }

        public virtual Usuario usuario { set; get;}
        public virtual Vehiculo vehiculo {set; get;}
    }
}

Autoventas/Controllers/ApartadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Autoventas.Models;

namespace Autoventas.Controllers
{
    public class ApartadoController : Controller
    {
        private DB_Autoventas db = new DB_Autoventas();

        // GET: Apartado
        public ActionResult Index(string search)
        {
            var reservas = from r in db.apartado
                            select r;
            if (!String.IsNullOrEmpty(search))
            {
                reservas = reservas.Where(r => r.vehiculo.marca.ToString().Contains(search));
            }
            reservas = reservas.OrderBy(r => r.vehiculo.marca);

            return View(reservas.ToList());
        }
        public ActionResult Venta()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Venta(int? id, Venta venta)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartado apartado = db.apartado.Find(id);
            Vehiculo vehiculo = apartado.vehiculo;
            DateTime fecha;
            fecha = DateTime.Now.Date;
            if (apartado == null)
            {
                return HttpNotFound();
            }
            venta.vehiculo = vehiculo;
            venta.usuario = apartado.usuario;
            venta.fecha = fecha;
            venta.ganancia = vehiculo.precio - vehiculo.precioCompra;
            vehiculo.estado = "Vendido";
            db.venta.Add(venta);
            db.apartado.Remove(apartado);
            db.SaveChanges();
            return RedirectToAction("../Venta/Index");
        }

        // GET: Apartado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartado apartado = db.apartado.Find(id);
            if (apartado == null)
            {
                return HttpNotFound();
            }
            return View(apartado);
        }

        // GET: Apartado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Apartado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idApartado,fecha")] Apartado apartado)
        {
            if (ModelState.IsValid)
            {
                db.apartado.Add(apartado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartado);
        }

        // GET: Apartado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartado apartado = db.apartado.Find(id);
            if (apartado == null)
            {
                return HttpNotFound();
            }
            return View(apartado);
        }

        // POST: Apartado/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idApartado,fecha")] Apartado apartado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(apartado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(apartado);
        }

        // GET: Apartado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartado apartado = db.apartado.Find(id);
            if (apartado == null)
            {
                return HttpNotFound();
            }
            return View(apartado);
        }

        // POST: Apartado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Apartado apartado = db.apartado.Find(id);
            db.apartado.Remove(apartado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Autoventas/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Autoventas.Models;
using System.Drawing;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace Autoventas.Controllers
{
    public class VehiculoController : Controller
    {
        private DB_Autoventas db = new DB_Autoventas();

        // GET: Vehiculo
        public ActionResult Index(string search)
        {
            @ViewBag.separar = "|";
            var vehiculos = from v in db.vehiculo  
                           select v;
            if (!String.IsNullOrEmpty(search))
            {
                vehiculos = vehiculos.Where(v => v.marca.ToString().Contains(search)
                                            || v.modelo.Contains(search)
                                            || v.tipo.ToString().Contains(search)
                                            || v.combustible.ToString().Contains(search));
            }
            vehiculos = vehiculos.OrderBy(v => v.marca);
            
            return View(vehiculos.ToList());
        }

        // GET: Vehiculo/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.apartar = "|";
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.vehiculo.Find(id);

            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }
        public ActionResult Venta()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Venta(int? id, Venta venta)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.vehiculo.Find(id);
            Usuario usuario = db.usuario.Find(Session["idUsuario"]);
            DateTime fecha;
            fecha = DateTime.Now.Date;
            if (vehiculo == null || usuario==null)
            {
                return HttpNotFound();
            }
            venta.vehiculo = vehiculo;
            venta.usuario = usuario;
            venta.fecha = fecha;
            venta.ganancia = vehiculo.precio - vehiculo.precioCompra;
            vehiculo.estado = "Vendido";
            db.venta.Add(venta);
            db.SaveChanges();
            return Redireccion();
        }
        public ActionResult Apartado()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Apartado(int? id, Apartado apartado)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.vehiculo.Find(id);
            Usuario usuario = db.usuario.Find(Session["idUsuario"]);
            DateTime fecha;
            fecha = DateTime.Now.Date;
            if (vehiculo == null || usuario == null)
            {
                return HttpNotFound();
            }
            apartado.vehiculo = vehiculo;
            apartado.usuario = usuario;
            apartado.fecha = fecha;
            vehiculo.estado = "Apartado";
            db.apartado.Add(apartado);
            db.SaveChanges();
            return RedirectToAction("../Apartado/Index");
        }
        public ActionResult Redireccion()
        {
            return RedirectToAction("../Venta/Index");
        }
        // GET: Vehiculo/Create
        public ActionResult Create()
        {
            List<int> años = new List<int>();
            for (int a = DateTime.Now.Year; a >= 1930; a--)
            {
                años.Add(a);
            }
            ViewBag.Año = new SelectList(años, "Año");
            return View();
        }

        // POST: Vehiculo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idVehiculo,imagen,marca,modelo,año,color,precioCompra, precio,estado,combustible,tipo")] Vehiculo vehiculo, HttpPostedFileBase archivo)
        {
            if (ModelState.IsValid)
            {
                if (archivo != null && archivo.ContentLength>0)
                {
                    var imagen = new Archivo
                    {
                        nombre =  System.IO.Path.GetFileName(archivo.FileName),
                        tipo =FileType.Imagen,
                        contentType=archivo.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(archivo.InputStream))
                    {
                        imagen.contenido = reader.ReadBytes(archivo.ContentLength);
                    };
                    vehiculo.archivos = new List<Archivo> { imagen };
                }

                List<String> años = new List<String>();
                for (int a = DateTime.Now.Year; a > 1930; a--)
                {
                    años.Add(a.ToString());
                }

                ViewBag.Año = new SelectList(años, "", "", vehiculo.año);

                vehiculo.estado = "En Venta";
                db.vehiculo.Add(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehiculo);
        }

        // GET: Vehiculo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            List<int> años = new List<int>();
            for (int a = DateTime.Now.Year; a >= 1930; a--)
            {
                años.Add(a);
            }
            ViewBag.Año = new SelectList(años, "Año");
            return View(vehiculo);
        }

        // POST: Vehiculo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName ("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, HttpPostedFileBase archivo)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vehiculo = db.vehiculo.Find(id);
            if(TryUpdateModel(vehiculo,"", new String[]{"idVehiculo,marca,modelo,año,color,precio,estado,combustible,tipo"} )){
                try{
                    if(archivo!=null && archivo.ContentLength>0){
                        if(vehiculo.archivos.Any(i => i.tipo==FileType.Imagen)){
                            db.archivo.Remove(vehiculo.archivos.First(i => i.tipo == FileType.Imagen));
                        }
                        var imagen = new Archivo
                        {
                            nombre = System.IO.Path.GetFileName(archivo.FileName),
                            tipo = FileType.Imagen,
                            contentType = archivo.ContentType
                        };
                        using(var reader= new System.IO.BinaryReader(archivo.InputStream))
                        {
                            imagen.contenido = reader.ReadBytes(archivo.ContentLength);
                        }
                        vehiculo.archivos = new List<Archivo> { imagen };
                    }
                    db.Entry(vehiculo).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }catch(RetryLimitExceededException ex){
                    ModelState.AddModelError("", "Unable to save changes. Try again.");
                }
            }
            List<String> años = new List<String>();
            for (int a = DateTime.Now.Year; a > 1930; a--)
            {
                años.Add(a.ToString());
            }

            ViewBag.Año = new SelectList(años, "", "", vehiculo.año);
            return View(vehiculo);
        }

        // GET: Vehiculo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.vehiculo.Find(id);

            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, HttpPostedFileBase x)
        {
            var vehiculo = db.vehiculo.Find(id);

            Archivo archivo = db.archivo.FirstOrDefault(a => a.idVehiculo == id);
            if (archivo != null)
            {
                db.archivo.Remove(archivo);
            }

            db.vehiculo.Remove(vehiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Catalogo(string search)
        {
            ViewBag.apartar = "|";
            var vehiculos = from v in db.vehiculo
                            select v;
            if (!String.IsNullOrEmpty(search))
            {
                vehiculos = vehiculos.Where(v => v.marca.ToString().Contains(search)
                                            || v.modelo.Contains(search)
                                            || v.tipo.ToString().Contains(search)

Autoventas/Views/Vehiculo/Apartado.cshtml
@model Autoventas.Models.Apartado

@{
    ViewBag.Title = "Apartado";
}

<h2>Apartado</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Apartar Vehiculo?</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <h2>Debera pagar este vehiculo en una semana</h2>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Catalogo")
</div>

Autoventas/Views/Vehiculo/Catalogo.cshtml
@using Autoventas.Models;
@model IEnumerable<Autoventas.Models.Vehiculo>
@{
    ViewBag.Title = "Catalogo";
}
<style>
    div .img {
        min-height: 200px;
    }
</style>
<h2>Vehiculo</h2>
@using (Html.BeginForm())
{
    <p>
        Puedes Buscar Vehiculos Por Marca, Modelo, Tipo o Combustible: <br />@Html.TextBox("search")
        <input type="image" src="~/Recursos/Imgenes/buscar.png" height="50" width="50" align="bottom" />
    </p>
}
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.estado.Equals("En Venta"))
            {
                <div>
                    <div class="col-sm-4 -md-4">
                        <div class="thumbnail">
                            @if (item.archivos != null)
                            {
                                <img src="~/Archivo/ObtenerArchivo?id=@item.archivos.First(f => f.tipo== Autoventas.Models.FileType.Imagen).idArchivo" alt="Imagen" class="img" height="175" width="350" />
                            }
                            <div class="caption">
                                @Html.Label("Marca:") @Html.DisplayFor(modelItem => item.marca)<br />
                                @Html.Label("Modelo:") @Html.DisplayFor(modelItem => item.modelo)<br />
                                @Html.Label("Año :") @Html.DisplayFor(modelItem => item.año)<br />
                                @Html.Label("Color") @Html.DisplayFor(modelItem => item.color)<br />
                                @Html.Label("Precio Q") @Html.DisplayFor(modelItem => item.precio)<br />
                                @Html.Label("Combustible") @Html.DisplayFor(modelItem => item.combustible)<br />
                                @Html.Label("Tipo de Vehiculo") @Html.DisplayFor(modelItem => item.tipo)<br />
                                @Html.ActionLink("Detalles", "Details", new { id = item.idVehiculo })<br />
                                @if (Session["idRol"] != null)
                                {
                                    if ("2".Equals(Session["idRol"].ToString()))
                                    {
                                        @Html.ActionLink("Comprar", "Venta", new { id = item.idVehiculo })<br />
                                        @Html.ActionLink("Apartar", "Apartado", new { id = item.idVehiculo })
                                    }
                                    if ("1".Equals(Session["idRol"].ToString()))
                                    {
                                        @Html.ActionLink("Editar", "Edit", new { id = item.idVehiculo })<br />
                                        @Html.ActionLink("Eliminar", "Delete", new { id = item.idVehiculo })
                                    }
                                }
                            </div>
                        </div>
                        <br />
                    </div>
                </div>
            }
        }
    </div>

Autoventas/Views/Vehiculo/Create.cshtml
@model Autoventas.Models.Vehiculo

@{
    ViewBag.Title = "Create";
}

<h2>Agregar</h2>


@using (Html.BeginForm("Create", "Vehiculo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (Session["idUsuario"]!=null)
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("foto", new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                <input type="file" id="foto" name="archivo" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.marca, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Año", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.año, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.color, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.precioCompra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precioCompra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precioCompra, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.combustible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.combustible, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.combustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.tipo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-success" />
            </div>
        </div>
    </div>
   }
}
@if (Session["idUsuario"] == null)
{
    <h2>Debe Iniciar Sesion</h2>
}
<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Autoventas/Views/Vehiculo/Edit.cshtml
@model Autoventas.Models.Vehiculo

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm("Edit", "Vehiculo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idVehiculo)

        @if (Model.archivos.Any(arch => arch.tipo == Autoventas.Models.FileType.Imagen))
        {
            <div class="form-group">
                <span class="control-label col-md-2"><strong>Imagen Actual</strong></span>
                <div class="col-md-10">
                    <img src="~/Archivo/ObtenerArchivo?id=@Model.archivos.First(f => f.tipo== Autoventas.Models.FileType.Imagen).idArchivo" alt="imagen" height="80" width="80">
                </div>
            </div>
        }
        <div class="form-group">
            @Html.Label("Imagen", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="foto" name="archivo" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.marca, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.año, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Año", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.año, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.color, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.combustible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.combustible, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.combustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.tipo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar Cambios" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Autoventas/Views/Vehiculo/Venta.cshtml
@model Autoventas.Models.Venta

@{
    ViewBag.Title = "Compra";
}

<h2>Comprar Un Vehiculo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Forma de Pago</h3>
        <h4>Elige la forma en que pagaras este vehiculo...</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.forma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.forma, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.forma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar Compra" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancelar", "Catalogo")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>